CREATE TABLE IF NOT EXISTS `navigation_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nav_key` VARCHAR(120) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `route` VARCHAR(255) NOT NULL,
  `location` VARCHAR(40) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `auth_required` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_system` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_navigation_items_key` (`nav_key`),
  KEY `idx_navigation_items_location_status` (`location`, `enabled`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `navigation_items` (`nav_key`, `name`, `route`, `location`, `enabled`, `auth_required`, `sort_order`) VALUES
('header_home', 'Home', '/', 'header', 1, 0, 10),
('header_search', 'Search', '/search', 'header', 1, 0, 20),
('header_login', 'Login', '/login', 'header', 1, 0, 30),
('header_register', 'Register', '/register', 'header', 1, 0, 40),
('header_profile', 'Profile', '/profile', 'header', 1, 1, 50),
('sidebar_home', 'Home', '/', 'left_sidebar', 1, 0, 10),
('sidebar_latest_posts', 'Latest Posts', '/search', 'left_sidebar', 1, 0, 20),
('sidebar_news', 'News', '/news', 'left_sidebar', 1, 0, 30),
('sidebar_business_directory', 'Business Directory', '/business-directory', 'left_sidebar', 1, 0, 40),
('sidebar_trending', 'Trending', '/search?tab=trending', 'left_sidebar', 1, 0, 50),
('sidebar_donation', 'Donation', '/donation', 'left_sidebar', 1, 0, 60),
('sidebar_help_center', 'Help Center', '/help-center', 'left_sidebar', 1, 0, 70),
('sidebar_profile', 'My Profile', '/profile', 'left_sidebar', 1, 1, 80),
('sidebar_settings', 'Settings', '/settings', 'left_sidebar', 1, 1, 90),
('sidebar_cms_pages', 'Pages', '/pages', 'left_sidebar', 1, 0, 100),
('sidebar_create_post', 'Create Post', '/post/new', 'left_sidebar', 1, 1, 110),
('sidebar_login', 'Login', '/login', 'left_sidebar', 1, 0, 120),
('sidebar_register', 'Register', '/register', 'left_sidebar', 1, 0, 130),
('mobile_home', 'Home', '/', 'mobile', 1, 0, 10),
('mobile_search', 'Search', '/search', 'mobile', 1, 0, 20),
('mobile_create_post', 'New', '/post/new', 'mobile', 1, 1, 30),
('mobile_join', 'Join', '/register', 'mobile', 1, 0, 30),
('mobile_profile', 'Profile', '/profile', 'mobile', 1, 1, 40),
('mobile_login', 'Login', '/login', 'mobile', 1, 0, 40),
('mobile_menu', 'Menu', '#menu', 'mobile', 1, 0, 50),
('footer_home', 'Home', '/', 'footer', 1, 0, 10),
('footer_search', 'Explore Posts', '/search', 'footer', 1, 0, 20),
('footer_news', 'News', '/news', 'footer', 1, 0, 30),
('footer_login', 'Login', '/login', 'footer', 1, 0, 40),
('footer_register', 'Register', '/register', 'footer', 1, 0, 50),
('footer_about', 'About Us', '/pages/about-us', 'footer', 1, 0, 60),
('footer_contact', 'Contact Us', '/pages/contact-us', 'footer', 1, 0, 70),
('footer_help_center', 'Help Center', '/help-center', 'footer', 1, 0, 80),
('footer_privacy', 'Privacy Policy', '/pages/privacy-policy', 'footer', 1, 0, 90),
('footer_terms', 'Terms & Conditions', '/pages/terms-conditions', 'footer', 1, 0, 100),
('footer_guidelines', 'Community Guidelines', '/pages/community-guidelines', 'footer', 1, 0, 110),
('footer_create_post', 'Create Post', '/post/new', 'footer', 1, 1, 120)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `route` = VALUES(`route`), `location` = VALUES(`location`), `auth_required` = VALUES(`auth_required`), `sort_order` = VALUES(`sort_order`);
