const quickComments = [
  // ==================== SHORT (1-3 words) ====================
  "Nice 👍",
  "Good 👍",
  "Great 👍",
  "Awesome 👍",
  "Excellent 👍",
  "Amazing 👍",
  "Fantastic 🔥",
  "Superb 💯",
  "Outstanding 🌟",
  "Wonderful ✨",
  "Perfect 👌",
  "Brilliant 💡",
  "Impressive 👏",
  "Lovely ❤️",
  "Beautiful 😍",
  "Stunning ✨",
  "Incredible 🤯",
  "Magnificent 🌟",
  "Phenomenal 💪",
  "Exceptional 👏",
  "Fabulous 💃",
  "Terrific 🔥",
  "Marvelous 🌟",
  "Splendid ✨",
  "Awesome Sauce 💯",
  "Epic 🏆",
  "Legend 💯",
  "Goat 🐐",
  "Classic 👌",
  "Solid 💪",
  "Cool 😎",
  "Lit 🔥",
  "Dope 🔥",
  "Fire 🔥",
  "Vibe ✨",
  "WOW 😲",
  "OMG 😱",
  "Yesss 🙌",
  "Yay 🎉",
  "Whoa 🤯",
  "Damn 🔥",
  "Sheesh 💯",
  "Bet 💪",
  "Facts 💯",
  "Truth ✅",
  "Real 💯",
  "Facts Only 💯",
  "No Cap 🧢",
  "Fr Fr 💯",
  "Big W 🏆",
  "W Moment 🎉",
  "Big Up 🙌",
  "Salute 🫡",
  "Respect 🙏",
  "Prayers 🙏",
  "Blessings 🙏",

  // ==================== SHORT APPRECIATION ====================
  "Very Nice 😊",
  "Keep It Up 👏",
  "Well Done 🌟",
  "Keep Growing 🚀",
  "Best Wishes 😊",
  "Proud Of You 💪",
  "Much Appreciated 🙌",
  "Well Said 👏",
  "Absolutely Right ✅",
  "True Words 💯",
  "Fully Agree 🤝",
  "Great Point 💡",
  "Excellent View 🌟",
  "Beautiful Thought ❤️",
  "Inspiring Words ✨",
  "So True 💯",
  "Big Facts 💯",
  "Preach 🙌",
  "Facts 💯",
  "Truth Bomb 💣",
  "Real Talk 💯",
  "No Lies ✅",
  "Pure Facts 💯",
  "Straight Up 💯",
  "On Point 🎯",
  "Nailed It 🎯",
  "Hit The Nail 💯",
  "That's It 💯",
  "This 💯",
  "That Part 💯",

  // ==================== CONGRATULATIONS ====================
  "Congratulations 🎉",
  "Many Congratulations 🎊",
  "Congrats Bro 🎉",
  "Congrats Sis 🎉",
  "Congrats Dude 🎉",
  "Congrats Buddy 🎉",
  "Heartiest Congratulations 🎊",
  "Congratulations On Your Success 🎉",
  "Congratulations On Your Achievement 🏆",
  "Congratulations On Your New Journey 🚀",
  "You Deserve This Success 🎉",
  "Wishing You Success 🚀",
  "Keep Shining ✨",
  "Wishing You More Success 🚀",
  "Congratulations On Your Promotion 🎉",
  "Congratulations On Your Wedding 💍",
  "Congratulations On Your Baby 👶",
  "Congratulations On Your New House 🏠",
  "Congratulations On Your New Car 🚗",
  "Congratulations On Your New Job 💼",
  "Congratulations On Your Graduation 🎓",
  "Congratulations On Your Engagement 💍",
  "Congratulations On Your Retirement 🎉",
  "Congratulations On Your Award 🏆",
  "Congratulations On Your Record 🏆",
  "Celebrating Your Success 🎊",
  "Your Hard Work Paid Off 💪",
  "Well Deserved Success 🏆",
  "You Earned It 🏆",
  "Victory Lap 🏆",
  "Champion 🏆",
  "Winner 🏆",
  "Number One 🥇",
  "Gold Medal 🥇",

  // ==================== BIRTHDAY ====================
  "Happy Birthday 🎂",
  "Happy Birthday Bhai 🎂",
  "Happy Birthday Brother 🎂",
  "Happy Birthday Sister 🎂",
  "Happy Birthday Dear 🎉",
  "Happy Birthday Buddy 🎂",
  "Happy Birthday Friend 🎂",
  "Happy Birthday Bestie 🎂",
  "Happy Birthday Love ❤️",
  "Happy Birthday Baby 😘",
  "Happy Birthday Sweetheart 💕",
  "Happy Birthday Champ 🏆",
  "Happy Birthday Legend 💯",
  "Happy Birthday King 👑",
  "Happy Birthday Queen 👑",
  "Happy Birthday Star ⭐",
  "Happy Birthday Angel 😇",
  "Happy Birthday Sunshine ☀️",
  "Many Happy Returns 🎂",
  "Wishing You A Great Year 🎉",
  "May All Your Wishes Come True 🎂",
  "Have A Blast On Your Birthday 🎊",
  "Happy Birthday To You 🎂",
  "Birthday Wishes 🎉",
  "God Bless You On Your Birthday 🙏",
  "Another Year Wiser 🎂",
  "Age Is Just A Number 🎂",
  "Forever Young 🎂",
  "Birthday Vibes 🎉",
  "Birthday Boy 🎂",
  "Birthday Girl 🎂",
  "Birthday Queen 👑",
  "Birthday King 👑",
  "Birthday Celebrations 🎊",

  // ==================== FATHERS DAY ====================
  "Happy Father's Day 👨‍👧‍👦❤️",
  "Happy Father's Day Dad 👨",
  "Happy Father's Day Papa 👨",
  "Happy Father's Day Abbu 👨",
  "World's Best Dad 👨",
  "Best Dad Ever 👨❤️",
  "Super Dad 💪",
  "Hero Dad 🦸",
  "Legend Dad 💯",
  "Father's Day Mubarak 👨",
  "Proud Of You Dad 💪",
  "Love You Dad ❤️",
  "Thank You Dad 🙏",
  "You Are My Hero Dad 🦸",
  "Dad You Are The Best 👨",
  "Best Father In The World 🌍",
  "Father's Day Special 👨",
  "Dad's Day ❤️",
  "Papa Mubarak 👨",
  "Abbu Mubarak 👨",

  // ==================== MOTHERS DAY ====================
  "Happy Mothers Day 👩‍👧‍👦❤️",
  "Happy Mothers Day Mom 👩",
  "Happy Mothers Day Mummy 👩",
  "Happy Mothers Day Ammi 👩",
  "Happy Mothers Day Ma 👩",
  "World's Best Mom 👩",
  "Best Mom Ever 👩❤️",
  "Super Mom 💪",
  "Queen Mom 👑",
  "Mom You Are The Best 👩",
  "Love You Mom ❤️",
  "Thank You Mom 🙏",
  "You Are My Strength Mom 💪",
  "Best Mother In The World 🌍",
  "Mothers Day Special 👩",
  "Mummy Mubarak 👩",
  "Ammi Mubarak 👩",
  "Ma Mubarak 👩",
  "Mom's Day ❤️",
  "Greatest Mom Ever 👩",

  // ==================== PARENTS DAY ====================
  "Happy Parents Day ❤️",
  "Happy Parents Day Mom Dad ❤️",
  "World Parents Day ❤️",
  "Best Parents Ever ❤️",
  "Proud Of My Parents 💪",
  "Love My Parents ❤️",
  "Thank You Parents 🙏",
  "Parents Are The Best ❤️",
  "My Everything ❤️",
  "Blessed With Best Parents 🙏",

  // ==================== FAMILY ====================
  "Happy Family Day 👨‍👩‍👧‍👦",
  "Family First ❤️",
  "Stay Blessed Together 🙏",
  "Family Time ❤️",
  "Family Love ❤️",
  "Family Bond ❤️",
  "Forever Family ❤️",
  "My Family My Life ❤️",
  "Family Matters ❤️",
  "Together Forever ❤️",

  // ==================== CHILDRENS DAY ====================
  "Happy Children's Day 👶",
  "Happy Children's Day Kids 👶",
  "Children Are The Future 🌟",
  "Love All Kids ❤️",
  "Kids Are Blessings 🙏",
  "Childhood Memories ❤️",
  "Happy Bal Diwas 👶",
  "Children's Day Mubarak 👶",

  // ==================== TEACHERS DAY ====================
  "Happy Teachers Day 📚",
  "Happy Teachers Day Sir 🙏",
  "Happy Teachers Day Ma'am 🙏",
  "Best Teacher Ever 📚",
  "Thank You Teacher 🙏",
  "Teachers Are Heroes 🦸",
  "Guru Mubarak 📚",
  "Teacher's Day Special 📚",
  "Salute To All Teachers 🫡",

  // ==================== DOCTORS DAY ====================
  "Happy Doctors Day 🩺",
  "Happy Doctors Day Sir 🙏",
  "Best Doctor Ever 🩺",
  "Thank You Doctor 🙏",
  "Doctors Are Angels 😇",
  "Salute To All Doctors 🫡",
  "Healthcare Heroes 🦸",
  "Doctor's Day Special 🩺",

  // ==================== ENGINEERS DAY ====================
  "Happy Engineers Day ⚙️",
  "Best Engineer Ever ⚙️",
  "Engineers Are Builders 🏗️",
  "Salute To All Engineers 🫡",
  "Engineer's Day Special ⚙️",
  "Problem Solvers 💡",

  // ==================== FARMERS DAY ====================
  "Happy Farmers Day 🌾",
  "Happy Farmers Day Kisan 🌾",
  "Thank You Farmers 🙏",
  "Farmers Are Backbone 💪",
  "Salute To All Farmers 🫡",
  "Jai Jawan Jai Kisan 🇮🇳",
  "Kisan Mubarak 🌾",

  // ==================== LABOR DAY / WORKERS DAY ====================
  "Happy Labor Day 👷",
  "Happy Workers Day 🔧",
  "Happy Labour Day 👷",
  "Salute To All Workers 🫡",
  "Workers Are Heroes 🦸",
  "Hard Work Pays Off 💪",
  "Respect All Workers 🙏",

  // ==================== NURSES DAY ====================
  "Happy Nurses Day 👩‍⚕️",
  "Happy Nurses Day 🧑‍⚕️",
  "Thank You Nurses 🙏",
  "Nurses Are Angels 😇",
  "Salute To All Nurses 🫡",
  "Healthcare Heroes 🦸",

  // ==================== FESTIVALS - DIWALI ====================
  "Happy Diwali 🪔",
  "Diwali Mubarak 🪔",
  "Shubh Deepawali 🪔",
  "Happy Diwali To All 🪔",
  "Diwali Ki Shubhkamnayein 🪔",
  "Festival Of Lights 🪔",
  "Light Over Darkness 🪔",
  "Happy Diwali Family 🪔",
  "Diwali Celebration 🎆",
  "Rangoli And Diyas 🪔",

  // ==================== FESTIVALS - HOLI ====================
  "Happy Holi 🌈",
  "Holi Hai 🌈",
  "Happy Holi To All 🌈",
  "Holi Mubarak 🌈",
  "Festival Of Colors 🌈",
  "Colors Of Joy 🌈",
  "Happy Holi Family 🌈",
  "Holi Celebration 🎨",
  "Gulal And Pichkari 🌈",
  "Holi Hai Bhai 🌈",

  // ==================== FESTIVALS - RAKSHA BANDHAN ====================
  "Happy Raksha Bandhan 🎁",
  "Rakhi Mubarak 🎁",
  "Happy Rakhi 🎁",
  "Rakhi Celebration 🎁",
  "Brother Sister Bond ❤️",
  "Raksha Bandhan Mubarak 🎁",
  "Happy Rakhi To All 🎁",
  "Rakhi Special 🎁",

  // ==================== FESTIVALS - JANMASHTAMI ====================
  "Happy Janmashtami 🦚",
  "Janmashtami Mubarak 🦚",
  "Krishna Janmashtami 🦚",
  "Happy Krishna Jayanti 🦚",
  "Jai Shri Krishna 🦚",
  "Nand Ghar Anand 🦚",
  "Birth Of Lord Krishna 🦚",
  "Janmashtami Celebration 🦚",

  // ==================== FESTIVALS - GANESH CHATURTHI ====================
  "Happy Ganesh Chaturthi 🐘",
  "Ganpati Bappa Morya 🐘",
  "Ganesh Chaturthi Mubarak 🐘",
  "Bappa Morya 🐘",
  "Ganpati Celebration 🐘",
  "Ganesh Utsav 🐘",

  // ==================== FESTIVALS - NAVRATRI ====================
  "Happy Navratri 💃",
  "Navratri Mubarak 💃",
  "Maa Durga Ki Jai 🙏",
  "Navratri Celebration 💃",
  "Nine Nights Of Dance 💃",
  "Garba Night 💃",
  "Dandiya Night 💃",

  // ==================== FESTIVALS - DUSSEHRA ====================
  "Happy Dussehra 🏹",
  "Vijayadashami Mubarak 🏹",
  "Dussehra Mubarak 🏹",
  "Victory Of Good Over Evil 🏹",
  "Ravan Dahan 🏹",
  "Happy Vijayadashami 🏹",
  "Dussehra Celebration 🏹",

  // ==================== FESTIVALS - MAKAR SANKRANTI ====================
  "Happy Makar Sankranti 🪁",
  "Sankranti Mubarak 🪁",
  "Kite Festival 🪁",
  "Happy Sankranti 🪁",
  "Til Gul Ghya 🪁",
  "Sankranti Celebration 🪁",

  // ==================== FESTIVALS - LOHRI ====================
  "Happy Lohri 🔥",
  "Lohri Mubarak 🔥",
  "Lohri Celebration 🔥",
  "Bonfire Night 🔥",

  // ==================== FESTIVALS - EID ====================
  "Happy Eid 🌙",
  "Eid Mubarak 🌙",
  "Eid Ul Fitr Mubarak 🌙",
  "Eid Ul Adha Mubarak 🌙",
  "Eid Celebration 🌙",
  "Eid Mubarak To All 🌙",
  "Eid Wishes 🌙",
  "Meethi Eid Mubarak 🌙",
  "Bakri Eid Mubarak 🌙",

  // ==================== FESTIVALS - CHRISTMAS ====================
  "Happy Christmas 🎄",
  "Merry Christmas 🎄",
  "Christmas Mubarak 🎄",
  "Jingle Bells 🎄",
  "Santa Claus 🎅",
  "Christmas Celebration 🎄",
  "Happy Holidays 🎄",
  "Christmas Wishes 🎄",

  // ==================== FESTIVALS - NEW YEAR ====================
  "Happy New Year 🎉",
  "New Year Mubarak 🎉",
  "Happy New Year 2024 🎉",
  "New Year Celebration 🎉",
  "New Year Wishes 🎉",
  "Happy New Year To All 🎉",
  "Cheers To New Year 🥂",
  "New Beginnings 🎉",

  // ==================== FESTIVALS - REPUBLIC DAY ====================
  "Happy Republic Day 🇮🇳",
  "Republic Day Mubarak 🇮🇳",
  "Happy 26 January 🇮🇳",
  "Proud Indian 🇮🇳",
  "Jai Hind 🇮🇳",
  "Vande Mataram 🇮🇳",

  // ==================== FESTIVALS - INDEPENDENCE DAY ====================
  "Happy Independence Day 🇮🇳",
  "15 August Mubarak 🇮🇳",
  "Happy 15 August 🇮🇳",
  "Freedom Day 🇮🇳",
  "Proud To Be Indian 🇮🇳",
  "Azadi Ka Amrit Mahotsav 🇮🇳",

  // ==================== FESTIVALS - GANDHI JAYANTI ====================
  "Happy Gandhi Jayanti 🇮🇳",
  "Gandhi Jayanti Mubarak 🇮🇳",
  "Mahatma Gandhi 🙏",
  "Bapu 🙏",
  "Father Of Nation 🇮🇳",

  // ==================== FESTIVALS - AMBEDKAR JAYANTI ====================
  "Happy Ambedkar Jayanti 🇮🇳",
  "Babasaheb Ambedkar 🙏",
  "Ambedkar Jayanti Mubarak 🇮🇳",
  "Father Of Constitution 📜",

  // ==================== FESTIVALS - PONGAL ====================
  "Happy Pongal 🎉",
  "Pongal Mubarak 🎉",
  "Pongal Celebration 🎉",
  "Harvest Festival 🌾",

  // ==================== FESTIVALS - ONAM ====================
  "Happy Onam 🌸",
  "Onam Mubarak 🌸",
  "Onam Celebration 🌸",
  "Onam Sadya 🍛",

  // ==================== FESTIVALS - UGADI ====================
  "Happy Ugadi 🎊",
  "Ugadi Mubarak 🎊",
  "Ugadi Celebration 🎊",

  // ==================== ANNIVERSARY ====================
  "Happy Anniversary 💐",
  "Happy Wedding Anniversary 💐",
  "Best Wishes For Anniversary 💐",
  "Marriage Anniversary Mubarak 💐",
  "Happy Anniversary To Both 🎉",
  "Wishing You Many More Years ❤️",
  "Happy Foundation Day 🎊",
  "Happy Establishment Day 🎉",
  "Happy Anniversary Bro 💐",
  "Happy Anniversary Sis 💐",
  "Anniversary Mubarak 💐",
  "Love Anniversary ❤️",

  // ==================== CONDOLENCE ====================
  "Om Shanti 🙏",
  "RIP 🕊️",
  "Tribute 🙏",
  "Respect 🙏",
  "Heartfelt Condolences 🙏",
  "May The Soul Rest In Peace 🕊️",
  "Our Thoughts Are With You 🙏",
  "Stay Strong 💐",
  "May God Give Strength 🙏",
  "Deepest Sympathy 🙏",
  "You Are In Our Prayers 🙏",
  "Peaceful Departure 🕊️",
  "Om Shanti Shanti Shanti 🙏",
  "RIP Brother 🕊️",
  "RIP Sister 🕊️",
  "RIP Legend 🕊️",

  // ==================== RELIGIOUS ====================
  "जय श्री राम 🚩",
  "जय सियाराम 🚩",
  "राधे राधे 🙏",
  "हर हर महादेव 🔱",
  "जय श्री कृष्ण 🙏",
  "जय माता दी 🙏",
  "सत श्री अकाल 🙏",
  "अल्लाह हाफ़िज़ 🌙",
  "ईश्वर आपका भला करे 🙏",
  "भगवान आपका मंगल करे 🙏",
  "राम राम सा 🙏",
  "जय भोलेनाथ 🔱",
  "जय गणेश 🐘",
  "जय साईं बाबा 🙏",
  "गुरु गोविंद दोनों खड़े 🙏",
  "जय श्री राम 🚩",
  "सिया राम 🚩",
  "राम राम 🙏",
  "सीता राम 🙏",
  "राधा कृष्ण 🙏",
  "शिव शिव 🔱",
  "जय गंगा मैया 🙏",
  "जय तुलसी माता 🙏",
  "जय सरस्वती माता 📚",
  "जय लक्ष्मी माता 💰",
  "जय दुर्गा माता 🙏",
  "जय काली माता 🔱",
  "जय भैरव बाबा 🔱",
  "जय हनुमान 🚩",
  "बम भोले 🔱",
  "शिव शंकर 🔱",
  "जय शंकर 🔱",

  // ==================== RESPECT & SALUTE ====================
  "Respect 🫡",
  "Salute To Your Effort 🫡",
  "Salute To Your Dedication 🫡",
  "Salute To Your Service 🫡",
  "True Inspiration 🚀",
  "Legend 💯",
  "Real Hero 💪",
  "Great Work 🌟",
  "You Are A Role Model 👏",
  "Salute To You Sir 🫡",
  "Salute To You Ma'am 🫡",
  "Respect Brother 🙏",
  "Respect Sister 🙏",
  "Respect Senior 🙏",
  "Salute 🫡",
  "Full Respect 🙏",
  "Mad Respect 🙏",
  "Big Respect 🙏",

  // ==================== SOCIAL WORK & COMMUNITY ====================
  "Excellent Social Work 🌱",
  "Great Initiative 👏",
  "Keep Serving Society 🤝",
  "Wonderful Community Service ❤️",
  "Proud Of Your Efforts 🌟",
  "Great Community Work 🤝",
  "Excellent Service 💪",
  "Selfless Service 🙏",
  "Inspiring Social Work 🌟",
  "Community First 🤝",
  "Village Pride 🌾",
  "Proud To Be Local 💪",
  "Neem Ka Thana Proud Moment ❤️",
  "Sikar Ka Beta/ Beti 💪",
  "Rajasthan Ka Gaurav 🌟",
  "Local Hero 💪",
  "Village Development 🌱",
  "Rural Development 🌾",
  "Great Initiative For Youth 👏",
  "Women Empowerment ❤️",
  "Education For All 📚",
  "Healthcare For All 🩺",
  "Support For Farmers 🌾",
  "Help For Needy 🤝",
  "Feeding The Hungry 🍛",
  "Plantation Drive 🌱",
  "Cleanliness Drive 🗑️",
  "Swachh Bharat Abhiyan 🧹",
  "Make India Clean 🇮🇳",
  "Save Water 💧",
  "Save Environment 🌱",
  "Tree Plantation 🌳",
  "Go Green 🌿",
  "Blood Donation ❤️",
  "Organ Donation 🙏",
  "Charity Work 🤝",

  // ==================== LEADERSHIP ====================
  "Excellent Leadership 👏",
  "Great Work For The Community 🌟",
  "People Are Proud Of You ❤️",
  "Keep Working For Society 🤝",
  "Your Efforts Are Appreciated 🙏",
  "Inspiring Leadership 🚀",
  "Great Vision 💡",
  "Selfless Leader 🙏",
  "True Leader 💪",
  "Born Leader 🌟",
  "Great Decision ✅",
  "Good Move 🎯",
  "Right Decision ✅",
  "Smart Move 💡",

  // ==================== SUPPORT & MOTIVATION ====================
  "Thank You 🙏",
  "Thanks For Sharing 📢",
  "Thanks For Support 🤝",
  "Thankful To You ❤️",
  "Much Thanks 🙏",
  "Inspirational 🌟",
  "Motivational 🚀",
  "Keep Supporting 🤝",
  "All The Best 🎯",
  "Good Luck 🍀",
  "Stay Blessed 🙏",
  "God Bless You 🙏",
  "Stay Happy 😊",
  "Stay Healthy 💚",
  "Keep Smiling 😊",
  "Sending Best Wishes 🌹",
  "Lots Of Love ❤️",
  "God Bless Your Family 🙏",
  "May God Bless You 🙏",
  "Stay Positive ✨",
  "Stay Strong 💪",
  "Keep Going 🚀",
  "Never Give Up 💪",
  "You Got This 💪",
  "Keep Moving 🚀",
  "Stay Focused 🎯",
  "Keep Grinding 💪",

  // ==================== WOMEN & GIRLS ====================
  "Happy Women's Day 👩",
  "Women Empowerment ❤️",
  "Nari Shakti 💪",
  "Beti Bachao Beti Padhao 📚",
  "Girl Child Education ❤️",
  "Respect Women 🙏",
  "Save The Girl Child 👧",
  "Happy Women's Day Mubarak 👩",
  "Women Power 💪",
  "Girl Power 👧",

  // ==================== POLITICAL & PUBLIC ====================
  "Jai Hind 🇮🇳",
  "Bharat Mata Ki Jai 🇮🇳",
  "Vande Mataram 🇮🇳",
  "Jai Jawan Jai Kisan 🇮🇳",
  "India First 🇮🇳",
  "Nation First 🇮🇳",
  "Proud Indian 🇮🇳",
  "Vocal For Local 🇮🇳",
  "Atmanirbhar Bharat 🇮🇳",
  "New India 🇮🇳",
  "Developed India 🇮🇳",
  "Digital India 🇮🇳",
  "Skill India 🇮🇳",
  "Make In India 🇮🇳",
  "Desh Bhakti 🇮🇳",
  "National Pride 🇮🇳",

  // ==================== LOVE & FRIENDSHIP ====================
  "Happy Friendship Day 🤝",
  "Happy Valentine's Day ❤️",
  "Love You All ❤️",
  "Best Friend Forever 🤝",
  "Brotherhood ❤️",
  "Sisterhood ❤️",
  "Unity Is Strength 🤝",
  "Together We Can 🤝",
  "Friendship Forever 🤝",
  "Besties For Life 🤝",
  "Love You Bro ❤️",
  "Love You Sis ❤️",
  "Love You Mom ❤️",
  "Love You Dad ❤️",
  "Love You Family ❤️",

  // ==================== HINDI APPRECIATION ====================
  "वाह बहुत बढ़िया 👏",
  "शानदार कार्य 🌟",
  "गर्व है आप पर 💪",
  "दिल जीत लिया ❤️",
  "बहुत खूब 🔥",
  "उत्तम प्रयास 👍",
  "कमाल कर दिया 💪",
  "लाजवाब 🔥",
  "बहुत सुंदर ❤️",
  "दमदार 💪",
  "शानदार सोच 💡",
  "सराहनीय कार्य 👏",
  "बहुत अच्छा 👍",
  "आपकी मेहनत रंग लाई 💪",
  "सच में बहुत अच्छा 😊",
  "आपसे सीखना चाहिए 📚",
  "बहुत प्रेरणादायक 🌟",
  "बढ़िया काम कर रहे हो 👏",
  "एकदम सही कहा ✅",
  "सच बोला 💯",
  "बहुत सही कहा 💯",
  "आप ने तो कमाल कर दिया 🔥",
  "क्या बात है 💪",
  "एक नंबर 💯",
  "टॉप क्लास 💯",
  "वाह वाह 👏",
  "बहुत बढ़िया जी 👏",

  // ==================== HINDI CELEBRATION ====================
  "मुबारक हो 🎉",
  "ढेर सारी शुभकामनाएं 🎊",
  "आपको हार्दिक बधाई 🎉",
  "जन्मदिन मुबारक 🎂",
  "शुभ जन्मदिन 🎂",
  "बहुत बहुत बधाई 🎉",
  "शादी की बधाई 💐",
  "आपकी सफलता पर गर्व 💪",
  "आपने कमाल कर दिया 🔥",
  "बधाई हो 🎉",
  "शुभकामनाएं 🎊",
  "ढेर सारी बधाई 🎉",

  // ==================== YOGA & WELLNESS ====================
  "Happy Yoga Day 🧘",
  "Namaste 🙏",
  "Stay Fit 💪",
  "Stay Healthy 💚",
  "Mental Peace 🧘",
  "Yoga For Life 🧘",
  "Meditation 🧘",
  "Healthy Living 💚",
  "Fitness First 💪",
  "Yoga Mubarak 🧘",

  // ==================== ENVIRONMENT ====================
  "Happy Environment Day 🌱",
  "Save Earth 🌍",
  "Go Green 🌿",
  "Plant More Trees 🌳",
  "Clean India Green India 🇮🇳",
  "Plastic Free India 🚫",
  "Zero Waste ♻️",
  "Save Water Save Life 💧",
  "Protect Environment 🌍",
  "Sustainable Living 🌱",
  "World Environment Day 🌍",
  "Beat Plastic Pollution 🚫",

  // ==================== EDUCATION ====================
  "Education Is Power 💪",
  "Learn And Grow 📚",
  "Education For All 📚",
  "Knowledge Is Power 💡",
  "Study Well 📚",
  "Success In Exams 🎯",
  "School Ka Beta/Beti 📚",
  "Padho Aur Badho 📚",

  // ==================== LOCAL VILLAGE PRIDE ====================
  "Gaon Ka Gaurav 🌾",
  "Mere Gaon Ki Shaan 🌟",
  "Rajasthan Pride 🌾",
  "Shekhawati Ka Beta/Beti 💪",
  "Neem Ka Thana Proud 🏠",
  "Sikar Pride 🌾",
  "Rajasthan Ki Shaan 🌟",
  "Mera Desh Mera Gaon 🇮🇳",
  "Desh Ki Seva Mein 🙏",
  "Gaon Ki Beti ❤️",
  "Gaon Ka Beta 💪",

  // ==================== GENERAL PRAISE ====================
  "You Are The Best 💯",
  "No One Like You 💪",
  "Simply The Best 🌟",
  "One Of A Kind ✨",
  "Truly Amazing 😍",
  "Absolutely Stunning ❤️",
  "Mind Blowing 🤯",
  "Out Of This World 🚀",
  "Pure Gold 💛",
  "Top Class 💯",
  "World Class 🌍",
  "Star Performer ⭐",
  "Game Changer 🎯",
  "Trailblazer 🚀",
  "Icon 💯",
  "Living Legend 💯",

  // ==================== ENCOURAGEMENT ====================
  "Don't Give Up 💪",
  "Keep Working Hard 💪",
  "You Can Do It 🎯",
  "Believe In Yourself 🙏",
  "Keep Pushing 🚀",
  "The Best Is Yet To Come 🌟",
  "Your Time Will Come 🎯",
  "Stay Focused 🎯",
  "Keep Dreaming Big 💭",
  "Sky Is The Limit 🚀",
  "Keep Hustling 💪",
  "Rise And Shine 🌅",

  // ==================== URGENT / IMMEDIATE ====================
  "At Your Service 🤝",
  "Always Ready To Help 💪",
  "With You Always ❤️",
  "Available For Support 🤝",
  "Just A Message Away 📱",
  "We Are With You ❤️",

  // ==================== APPRECIATION FOR POST ====================
  "Great Post 👏",
  "Very Informative 📖",
  "Thanks For Information 📢",
  "Good Knowledge 💡",
  "Nice Content 📝",
  "Great Article ✍️",
  "Helpful Post ✅",
  "Important Update 🔔",
  "Relevant Information ℹ️",
  "Useful Share 🔗",
  "Good Read 📖",
  "Valuable Information 💡",

  // ==================== MID SENTENCES (5-15 words) ====================
  "This is truly amazing and inspiring work, keep it up brother 🙏",
  "You have done a wonderful job, proud of your dedication 💪",
  "Such a great initiative for the community, highly appreciated 🌟",
  "Your hard work and dedication is an inspiration for all of us 🚀",
  "May God bless you and your family with lots of happiness 🙏",
  "This is what real leadership looks like, very impressive 👏",
  "You are making a real difference in people's lives, keep going ❤️",
  "Hats off to your commitment and passion for social work 🫡",
  "Your efforts are truly commendable and deserve all the praise 🌟",
  "This post made my day, thank you for sharing this positivity 😊",
  "Wishing you a very happy and blessed birthday, may all your dreams come true 🎂",
  "Congratulations on this wonderful achievement, you really deserve it 🎉",
  "Your selfless service to the society is truly inspiring and motivating 🙏",
  "This is the kind of work that builds a stronger and better community 🤝",
  "You are a true gem and we are lucky to have people like you 💎",
  "Keep shining and spreading positivity wherever you go ✨",
  "Your dedication towards your work is something everyone should learn from 💪",
  "What a fantastic post, this made my heart full of joy and hope ❤️",
  "Proud to be part of such a wonderful and supportive community 🌟",
  "Your words are so powerful and full of wisdom, thank you for sharing 📖",
  "Happy Fathers Day to all the amazing dads out there, you are the real heroes 👨‍👧‍👦",
  "Happy Mothers Day to the strongest women, love you all so much ❤️",
  "Sending lots of love and prayers to you and your beautiful family 🙏",
  "Your post reminded me of how important it is to help others selflessly 🤝",
  "This is the kind of positive change we need in our society today 🌟",
  "Your hard work is going to inspire generations to come, keep it up 🚀",
  "It takes a lot of courage and dedication to do what you are doing, respect 🫡",
  "Your journey is truly inspiring and gives hope to so many people 🙏",
  "The way you serve others with so much love is truly beautiful ❤️",
  "You are a blessing to this community, may you always be happy 🙏",
  "Happy Anniversary to a wonderful couple, your love is truly inspiring 💐",
  "Your content always brings a smile on my face, thank you for posting 😊",
  "What a beautiful post, this really touched my heart deeply ❤️",
  "Your dedication towards the betterment of society is remarkable 🌟",
  "Never stop doing what you love, because you are making a big difference 💪",
  "You are one of the most hardworking people I have ever seen, hats off 🫡",
  "This post is pure gold and should be seen by everyone, truly amazing 💛",
  "People like you make this world a better place to live in, thank you 🙏",
  "Your energy and positivity is contagious, keep spreading it around ✨",
  "This is a beautiful example of how we should all treat each other 🤝",
  "Happy Birthday Bhai, you are the best and I wish you all the success 🎂",
  "Your commitment towards helping others is truly applaudable and inspiring 👏",
  "May the blessings of God always shower upon you and your loved ones 🙏",
  "You are doing an outstanding job and we all are so proud of you 💪",
  "This made me emotional and proud to be part of this wonderful journey ❤️",
  "Your selfless efforts are going to change so many lives for the better 🌟",
  "What a legend you are, keep up the amazing work and never give up 💯",
  "Your work speaks volumes about your character and values, much respect 🫡",
  "The love and support you show to everyone is truly unconditional ❤️",
  "Your success story is a proof that hard work always pays off, keep going 🚀",
  "May you achieve all your goals and dreams, you deserve everything good 🙏",
  "Your vision and dedication will take you to great heights, best of luck 🎯",

  // ==================== LONG SENTENCES (15+ words) ====================
  "The way you have dedicated your life to serving others and making this world a better place is truly inspiring and commendable 🙏",
  "Congratulations on this massive achievement, you have worked so hard for this and you absolutely deserve all the success coming your way 🎉",
  "Your post has touched my heart in so many ways and I just want to say thank you for being such an amazing person and inspiration to all of us ❤️",
  "May God bless you with all the happiness, success, and love that this world has to offer because you truly deserve the very best in life 🙏",
  "The love, care, and dedication that you show towards your family and community is something that everyone should learn from and admire 🌟",
  "I have no words to describe how proud I am of you and everything that you have achieved through your hard work and determination 💪",
  "Your journey from nothing to something is a story that will inspire millions of people to never give up on their dreams no matter what 🚀",
  "The way you handle every situation with so much grace and maturity is a testament to the kind of person you truly are at heart ❤️",
  "I just want to take a moment to appreciate everything that you do for others without expecting anything in return, you are a true blessing 🙏",
  "May your life be filled with endless joy, boundless success, and unconditional love from everyone who is lucky enough to know you 😊",
  "Happy Birthday to the most amazing person I know, your presence in my life has been nothing short of a blessing from above 🎂",
  "Congratulations once again on this incredible achievement, you have proven that hard work, patience, and faith can move mountains 🏔️",
  "Your selfless service and dedication towards the upliftment of society is something that will be remembered for generations to come 🌟",
  "This is exactly the kind of positive change that our society needs right now and you are leading the way with your amazing work 👏",
  "You have inspired so many people including me to become better versions of ourselves and for that I will always be grateful to you 🙏",
  "Keep shining bright like a star and never let anyone dim your light because you are destined for greatness and success 💫",
  "The amount of love and respect that people have for you is a direct reflection of how beautiful your soul truly is ❤️",
  "Your hard work, dedication, and never-give-up attitude are the reasons why you have achieved so much success in life 💪",
  "I am so blessed and grateful to have you in my life and I pray that God always keeps you happy and healthy 🙏",
  "Your post has brought a smile on my face and positivity in my heart, thank you for spreading so much joy and happiness 😊",
  "Happy Fathers Day to all the amazing dads who work tirelessly to provide for their families and never ask for anything in return 👨‍👧‍👦",
  "Happy Mothers Day to the strongest women in the world who sacrifice everything for their children and love unconditionally ❤️",
  "Sending all my love, prayers, and best wishes to you and your beautiful family, may you always stay blessed and happy 🙏",
  "Your post reminded me how important it is to help others without any selfish motives, this is what humanity is all about 🤝",
  "The world needs more people like you who are willing to go the extra mile to make a positive difference in others' lives 🌟",
  "Your hard work and dedication will definitely inspire the next generation to work hard and serve society with love and compassion 🚀",
  "It takes a lot of courage, patience, and determination to do what you are doing and I have immense respect for you 🫡",
  "Your journey is a perfect example of how faith, hard work, and persistence can help you achieve anything you want in life 🙏",
  "The way you treat everyone with so much love, kindness, and respect is something that makes you stand out from the rest ❤️",
  "You are truly a blessing to this world and I pray that you continue to inspire and help others for many more years 🙏",
  "Happy Anniversary to both of you, your love story is an inspiration and proof that true love really exists ❤️💐",
  "Your content is always so engaging, informative, and full of positivity that I look forward to reading it every single day 😊",
  "This is one of the most beautiful posts I have ever seen, it touched my heart and made me believe in the power of love again ❤️",
  "Your dedication towards the betterment of society is unmatched and I am truly inspired by your selfless service 🌟",
  "Never stop doing what you love because you are making a huge difference in this world and in people's lives every day 💪",
  "You are hands down one of the most hardworking, dedicated, and passionate people I have ever had the pleasure of knowing 🫡",
  "This post is absolute gold and everyone needs to see it, your words have the power to change lives and spread positivity 💛",
  "People like you are rare gems who make this world a much better place to live in and I am so grateful for you 🙏",
  "Your energy and positivity are so infectious that they brighten up even the darkest days, keep spreading the light ✨",
  "This is a perfect example of how we should all treat each other with kindness, respect, and unconditional love 🤝",
  "Happy Birthday Bhai, you are the absolute best and I wish you nothing but success, happiness, and love in life 🎂",
  "Your commitment towards helping others and serving society is truly admirable and inspiring for everyone around you 👏",
  "May God always bless you, your family, and everything that you do with immense success and happiness 🙏",
  "You are doing absolutely outstanding work and all of us are incredibly proud of you and your achievements 💪",
  "This post made me so emotional and proud to be part of this wonderful journey with such amazing people ❤️",
  "Your selfless efforts and dedication are going to bring positive change and touch so many lives for the better 🌟",
  "You are an absolute legend, keep up the incredible work and never ever give up on your dreams 💯",
  "Your hard work, values, and character speak for themselves and I have so much respect for you and everything you do 🫡",
  "The love and support you show to everyone around you is truly unconditional and inspiring in every possible way ❤️",
  "Your success story is living proof that with hard work, dedication, and patience, you can achieve absolutely anything 🚀",
  "May you achieve all your dreams and goals because you deserve nothing but the very best in this world 🙏",
  "Your vision, determination, and dedication will definitely take you to the top and I wish you all the very best 🎯",
  "You are a true inspiration to millions and your work will leave a lasting impact on society for generations 🙏",
  "Thank you for being such a wonderful human being and for always spreading love, joy, and positivity everywhere ❤️",
];

export default quickComments;